import { Link } from 'react-router-dom';

function Section({ title, children }) {
  return (
    <section className="mb-8">
      <h2 className="mb-2 font-display text-xl font-semibold">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-muted">{children}</div>
    </section>
  );
}

export default function Privacy() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-12">
      <p className="mb-1 font-mono text-xs uppercase tracking-[0.2em] text-teal">Privacy</p>
      <h1 className="mb-2 font-display text-3xl font-bold">Privacy notice</h1>
      <p className="mb-8 text-sm text-muted">
        BizTransform is a student prototype built for a university unit (ICT313). This notice
        explains plainly what it does with your information, in line with the Australian Privacy
        Principles (Privacy Act 1988).
      </p>

      <Section title="Please don't enter sensitive information">
        <p>
          This is a prototype, not a hardened commercial service. Use it for the assessment
          questions it asks and nothing more — don't enter bank details, government identifiers,
          health information or anything else you would not want a developer to be able to see.
        </p>
      </Section>

      <Section title="What we collect, and why">
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <strong className="text-text">Account details</strong> — your name, email address and
            a password (stored only as a one-way hash, never in readable form), plus your role.
            Used to log you in.
          </li>
          <li>
            <strong className="text-text">Business details</strong> — business name and sector.
            Used to tailor questions and to compare you with similar businesses.
          </li>
          <li>
            <strong className="text-text">Assessment data</strong> — your yes/no answers, scores,
            roadmap actions, the progress you record and any cost or benefit figures you enter.
            Used to show your results and track improvement.
          </li>
          <li>
            <strong className="text-text">Website checks</strong> — the website address you ask us
            to check and the technical result.
          </li>
          <li>
            <strong className="text-text">Advisor notes</strong> — if you are linked to an advisor,
            notes they write about your business.
          </li>
          <li>
            <strong className="text-text">Security records</strong> — failed logins, password
            changes and administrator actions, with the time and your IP address. Used only to
            detect and investigate misuse.
          </li>
        </ul>
      </Section>

      <Section title="Who can see it">
        <ul className="list-disc space-y-1 pl-5">
          <li>
            <strong className="text-text">You</strong> can see your own data.
          </li>
          <li>
            <strong className="text-text">Advisors</strong> can see business accounts —
            including name, email, assessment results, roadmap progress, website checks and
            advisor notes. An advisor's main list shows the businesses linked to them (by an
            invite code, or because they created the account), but in this prototype any advisor
            account can also look up any other business on the platform. Anyone can register as
            an advisor, so please bear this in mind.
          </li>
          <li>
            <strong className="text-text">Platform administrators</strong> can see account details
            and security records, and can deactivate accounts.
          </li>
          <li>
            Sector comparisons use averages across businesses and don't show any one business's
            figures.
          </li>
        </ul>
      </Section>

      <Section title="Third parties">
        <p>
          If the service is configured with an AI key, your business name (or your own name if you
          didn't give one), sector, scores and answers are sent to Anthropic's Claude service to
          write your roadmap wording. Your email address is not sent. If no key is configured, or
          that service is unavailable, the roadmap is generated by built-in rules and nothing is
          sent.
        </p>
        <p>
          We don't use advertising, analytics or tracking tools, and we don't sell or share your
          information with anyone else.
        </p>
      </Section>

      <Section title="Cookies and local storage">
        <p>
          We don't use cookies. Your browser's local storage holds your login session and your
          light/dark theme choice, so you stay logged in. Logging out removes the session.
        </p>
      </Section>

      <Section title="Security">
        <p>
          Passwords are hashed, sessions expire after seven days or when you change your password,
          and repeated failed logins are temporarily blocked. No system is perfectly secure, which
          is another reason to keep sensitive details out of this prototype.
        </p>
      </Section>

      <Section title="Access, correction and deletion">
        <p>
          You can ask to see the information held about you, to have it corrected, or to have your
          account and its data deleted. As this is a student project, make the request to the
          project team through your course contact or the advisor who set you up, and we will act
          on it. You can also change your password yourself on the{' '}
          <Link to="/account" className="text-teal hover:underline">
            account page
          </Link>
          .
        </p>
        <p>
          If you are unhappy with how your information is handled, you can complain to the Office
          of the Australian Information Commissioner (oaic.gov.au).
        </p>
      </Section>
    </div>
  );
}
